# Stage 1: Build the application
FROM node:24-alpine AS builder

RUN apk upgrade --no-cache

WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Use the env variables during build
ARG VITE_DEFAULT_GEEKLIST_ID
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_GOOGLE_REDIRECT_URI

# Install dependencies using Yarn
RUN yarn install

# Copy the rest of the application files
COPY . .

# Build with the env var passed explicitly
RUN VITE_DEFAULT_GEEKLIST_ID=$VITE_DEFAULT_GEEKLIST_ID \
    VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID \
    VITE_GOOGLE_REDIRECT_URI=$VITE_GOOGLE_REDIRECT_URI \
    VITE_AUTH0_DOMAIN=$VITE_AUTH0_DOMAIN \
    VITE_AUTH0_CLIENT_ID=$VITE_AUTH0_CLIENT_ID \
    VITE_AUTH0_AUDIENCE=$VITE_AUTH0_AUDIENCE \
    yarn build

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

RUN apk upgrade --no-cache

COPY --from=builder /app/dist /usr/share/nginx/html
