services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173" # Vite
    volumes:
      - ./frontend:/app        # Mount the local frontend code into the container
      - /app/node_modules      # Prevent node_modules from being overwritten
    networks:
      - internal
      - default
    working_dir: /app
    command: sh -c "yarn dev"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - internal
      - default
    depends_on:
      - frontend